### ISSUE TITLE
missing instructions in step 2?

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/oauth-workshop#1]
Hi Jen, nice walkthrough, thanks! we did it earlier today in Nazareth.

Just wondering whether there were things missing (or whether we were missing something) in step 2? 

1. are we supposed to use env2 or similar to include the variables from config.env? We ended up needing to do so later in order to access the secret key, but didn't actually use the base url so not sure what that was for/whether this is what you intended.
2. are we supposed to include 'tls' inside server.connection? This is how we all ended up doing it, was this how you intended it to be done? (e.g. see [here](https://github.com/FACN1/palm-funday-auth/blob/master/server.js#L13) if you have access)

**Comment by jsms90** [comment]
Hey @mattlub! Great points! Thanks for the issue :tada: :clap:

I've seen `env2` used so often in the past few weeks, it didn't occur to me to instruct anyone to install it. But that's really silly, since I go through everything else step-by-step. Bit of an oversight.

And you're totally right about the `tls` parameter. I have it set up on my local machine from when I ran through this workshop myself. Don't know how it didn't make its way into the instructions. Doh!

Hooray for collaboration :dancer:

**Comment by jsms90** [comment]
As for the `BASE_URL`, [you have just hard-coded it into your app](https://github.com/FACN1/palm-funday-auth/blob/master/server.js#L37) instead. It's just nicer to be dealing with anything that is specific to your environment within your `.env` file, rather than changing the code of your application, if/when anything about your environment changes.

Perhaps it seems a little silly, since everyone is going to be using `localhost:xxxx`? I haven't been doing this long enough to be able to give you examples of where it's useful :thinking: but it makes sense to me, at least conceptually....does that help? Maybe ask @des-des?

**Comment by mattlub** [comment]
Ah yeh, I see that now about the base_url. Makes sense, thanks!

**Comment by jsms90** [comment]
@mattlub 
Thanks for pointing out the potential confusion in PR #2 !!
I had to merge it, because FAC10 are completing the workshop now.

I made your suggested change in https://github.com/foundersandcoders/oauth-workshop/commit/3c6c4438d4a04f8a5c8bce10c80d43fe2ac0fcb5
(Didn't reference this issue :scream: :crying_cat_face: )

Are you happy to close the issue?

**Comment by mattlub** [comment]
didn't reference the issue!?! 😮 
yep, no worries- all good now, I'll close it 👍

**Comment by des-des** [comment]
@mattlub @jsms90 the link to the hardcoded base_url is problematic because it would break if you deployed it to heroku, or anywhere, that code will only work locally, as in other places the url would be different.
